services:
  web-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:5000
      - ConnectionStrings__Database=Server=sql-server;Database=Library;User Id=sa;Password=Str0ng!Pass;TrustServerCertificate=True;Encrypt=False;MultipleActiveResultSets=true
    ports:
      - "5000:5000"
    depends_on:
      sql-server:
        condition: service_started

  web-ui:
    environment:
      - VITE_API_BASE_URL=http://localhost:5000
    ports:
      - "5002:5002"
    depends_on:
      - web-api